# -*- coding: utf-8 -*-
"""PYTHON_PROJECT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xzpa-mgROvSZYPbsGhhtSBM6n3eddzow
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/Customer Churn.csv")
df
df.shape
df.size
df.info()
df.Partner(20)

df.info()

df.Partner.head(20)

df.TotalCharges =df.TotalCharges.replace(" ","0")
df.TotalCharges =df.TotalCharges.astype("float")
df.TotalCharges

df.TotalCharges

df.isnull().sum().sum()

df.describe()

df.duplicated().sum()
df["customerID"].duplicated().sum()

"""replace the senier citizen value with o,1 to yes and no"""

def senier_cityzen(value):
  if   value ==0:
    return "no"
  else:
    return "yes";

  df["SeniorCityzen"]=df["SeniorCitizen"].apply(senier_cityzen)

# define function properly
def senior_citizen(value):
    if value == 0:
        return "no"
    else:
        return "yes"

# apply function to the column
df["SeniorCitizen"] = df["SeniorCitizen"].apply(senior_citizen)

# check first few values
df["SeniorCitizen"].head(5)

df.head(2)

"""COUNT the percentage of churn

"""

ax = sns.countplot(x="Churn",data=df)
plt.show()
ax.bar_label(ax.containers[0])
plt.show()

# Create the plot and store the axes in ax
ax = sns.countplot(x="Churn", data=df)

# Add bar labels on top of the bars
ax.bar_label(ax.containers[0])

# Show the plot
plt.show()

"""PERcentage of churn"""

gp = df.groupby("Churn").agg({"Churn":"count"})

plt.title("Percentage of Churn",fontsize=15,fontweight="bold")
plt.pie(gp["Churn"],labels=gp.index,autopct = "%1.3f%%")
plt.show()

#
#

from matplotlib import colors
plt.figure(figsize=(2,2))
plt.title("CHURN BY GENDER")
sns.countplot(x="gender",data=df,color="green",hue="Churn")
plt.show()

"""CHURN BY SENIOR CITYZEN (STACKED BY BAR CHART)"""

TOTAL_CHURN=df.groupby(["SeniorCitizen ","Churn"]).agg({"Churn":"count"})

plt.countplot(x="SeniorCitizen ",data=df,hue="Churn")
plt.show()
#

import pandas as pd
import matplotlib.pyplot as plt

# --- Step 1: Create the grouped data ---
# Count churn status for each SeniorCitizen group
#size() counts how many rows fall into each combination.

#.unstack() reshapes the table so that “Churn” values become columns.
churn_counts = df.groupby(['SeniorCitizen', 'Churn']).size().unstack()

# --- Step 2: Convert counts to percentage ---
churn_percent = churn_counts.div(churn_counts.sum(axis=1), axis=0) * 100
#axis=0 → Down the rows (vertical)#axis=1 → Across the columns (horizontal)

# --- Step 3: Plot stacked bar chart ---
churn_percent.plot(
    kind='bar',
    stacked=True,
    color=['#3498db', '#e67e22'],  # blue and orange
    figsize=(7,5)
)

# --- Step 4: Add labels and title ---
plt.title('Churn by Senior Citizen (Stacked Bar Chart)', fontsize=14)
plt.xlabel('Senior Citizen (0 = No, 1 = Yes)', fontsize=12)
plt.ylabel('Percentage (%)', fontsize=12)
plt.legend(title='Churn', loc='best')

# --- Step 5: Add percentage labels inside bars ---
for i, (idx, row) in enumerate(churn_percent.iterrows()):
    bottom = 0
    for churn_status, value in row.items():
        plt.text(
            i,                      # x position
            bottom + value / 2,     # y position (middle of bar segment)
            f"{value:.1f}%",        # label text
            ha='center', va='center', color='black', fontsize=10
        )
        bottom += value

plt.show()

sns.histplot(data=df,x="tenure",hue="Churn",bins=10)
plt.show()
#



# Group the data
gp01 = df.groupby(["gender", "PaymentMethod"]).agg({"MonthlyCharges": "sum"}).reset_index()
# Plot using seaborn
plt.figure(figsize=(10,6))
sns.barplot(x="PaymentMethod", y="MonthlyCharges", hue="gender", data=gp01)

plt.title("Total Monthly Charges by Payment Method and Gender")
plt.xticks(rotation=45)
plt.xlabel("Payment Method")
plt.ylabel("Total Monthly Charges")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,8))
plt.pie(
    gp01["MonthlyCharges"],        # values to plot
    labels=gp01["PaymentMethod"],  # category names
    autopct="%1.2f%%",             # show percentage
    startangle=90,                 # rotate start for better look
)
plt.title("Distribution of Monthly Charges by Payment Method")
plt.show()

plt.bar(df['gender'],df['MonthlyCharges'])
plt.bar(df['gender'],df['tenure'])
plt.title("Monthly Charges by Gender")
plt.xlabel("Gender")
legend_labels = ['Monthly Charges', 'Tenure']
plt.legend(legend_labels)
plt.ylabel("Monthly Charges")
plt.show()

# Group and calculate average for clarity
gp = df.groupby("gender")[["MonthlyCharges", "tenure"]].mean().reset_index()

# Set bar positions
x = np.arange(len(gp["gender"]))  # X locations for groups
width = 0.35  # Width of the bars

# Create bars
plt.figure(figsize=(8,6))
plt.bar(x - width/2, gp["MonthlyCharges"], width, label="Monthly Charges")
plt.bar(x + width/2, gp["tenure"], width, label="Tenure")

# Add titles and labels
plt.title("Average Monthly Charges and Tenure by Gender", fontsize=14)
plt.xlabel("Gender")
plt.ylabel("Average Value")
plt.xticks(x, gp["gender"])
plt.legend()
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# Set figure style
sns.set(style="whitegrid")

# Create a figure with multiple subplots
plt.figure(figsize=(18,12))

# --- 1️⃣ Bar Chart: Average Monthly Charges by Gender ---
plt.subplot(2,3,1)
sns.barplot(x="gender", y="MonthlyCharges", data=df, estimator=np.mean)
plt.title("Average Monthly Charges by Gender")
plt.xlabel("Gender")
plt.ylabel("Avg Monthly Charges")

# --- 2️⃣ Pie Chart: Distribution of Contract Types ---
plt.subplot(2,3,2)
contract_counts = df["Contract"].value_counts()
plt.pie(contract_counts, labels=contract_counts.index, autopct="%1.1f%%", startangle=90)
plt.title("Customer Distribution by Contract Type")

# --- 3️⃣ Histogram: Tenure Distribution ---
plt.subplot(2,3,3)
plt.hist(df["tenure"], bins=30, color='skyblue', edgecolor='black')
plt.title("Tenure Distribution")
plt.xlabel("Tenure (Months)")
plt.ylabel("Frequency")

# --- 4️⃣ Scatter Plot: Monthly Charges vs Total Charges ---
plt.subplot(2,3,4)
plt.scatter(df["MonthlyCharges"], df["TotalCharges"], alpha=0.5, color='green')
plt.title("Monthly Charges vs Total Charges")
plt.xlabel("Monthly Charges")
plt.ylabel("Total Charges")

# --- 5️⃣ Heatmap: Correlation between Numeric Variables ---
plt.subplot(2,3,5)
numeric_df = df.select_dtypes(include=['int64','float64'])
sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap")

# --- 6️⃣ Bar Chart: Customer Count by Internet Service ---
plt.subplot(2,3,6)
sns.countplot(x="InternetService", data=df, palette="pastel")
plt.title("Customer Count by Internet Service")
plt.xticks(rotation=20)

# Adjust layout to prevent overlap
plt.tight_layout()
plt.show()